### ISSUE TITLE
imagePath for Meteor 0.9.0

### ISSUE THREAD

**Issue by flox1an** [bevanhunt/meteor-leaflet#13]
For Meteor 0.9.0 the public images path has changed. The mrt:leaflet module generally works but the marker images are missing.

I have configured:
L.Icon.Default.imagePath = 'packages/leaflet/images'

which is not working any more. Until now I couldn't find a working path for the images in the migrated leaflet package.

**Comment by muvic08** [comment]
The image path stills throws "Resource interpreted as Image but transferred with MIME type text/html:" even after using both suggestions above.

**Comment by KyleKing** [comment]
Which version of meteor are you using? I'm using L.Icon.Default.imagePath = 'packages/mrt_leaflet/images' with Meteor 1.0.3.1 and that works

**Comment by muvic08** [comment]
Thanks KyleKing. I fixed it using your suggestion. In the current version of leaflet and meteor, username:packagename or username_packagename paths doesn't seem to work. From personal experience so far, I would recommend avoiding : or _ when naming packages.

**Comment by appshore** [comment]
In the last iteration (0.3.12) the path works as:

L.Icon.Default.imagePath = '/packages/bevanhunt_leaflet/images' ;

note the / at the beginning of the path.

**Comment by KyleKing** [comment]
I didn't realize the repository this thread was on
Use ``` L.Icon.Default.imagePath = 'leaflet/images'; ``` only for the mrt:leaflet package
