### ISSUE TITLE
update for the new meteor package system

### ISSUE THREAD

**Issue by lampe** [bevanhunt/meteor-leaflet#14]
Hey

will you update the package to the new meteor package system?
and maintain the package?

I could help if you need some.

**Comment by Ethaan** [comment]
Someone now which is the best package option to use leaflet on meteors project? 1.+

**Comment by willemx** [comment]
I am using fuatsengul:leaflet which more or less works (need to manually copy layers.png deep down the public folder...)
Hope there will be an "official" leaflet package for Meteor someday. (maybe when leaflet 1.0 arrives?)

**Comment by Ethaan** [comment]
@willemx can you point me where to find the layers.png etc? plc this  [this](https://github.com/Leaflet/Leaflet/tree/master/src/images ) one?

**Comment by bevanhunt** [comment]
This package as been fixed - it now supports the latest version of Meteor/Leaflet. Thanks to a PR https://github.com/bevanhunt/meteor-leaflet/pull/17 from AppShore and some tweaking. Cheers.
