### ISSUE TITLE
Layers control button image is not found on client

### ISSUE THREAD

**Issue by solo999** [bevanhunt/meteor-leaflet#18]
layers.png file path on client is:
url(packages/bevanhunt_leaflet/styles/images/layers.png)

but actual path is packages/bevanhunt_leaflet/images/layers.png

**Comment by bevanhunt** [comment]
Sorry for the delay - the new version of this package [0.3.13](https://github.com/bevanhunt/meteor-leaflet/releases/tag/0.3.13) should fix this problem. Thanks for the bug report.

**Comment by bevanhunt** [comment]
01b710a7372a2965090c9dca34ce8b7719663b49
