### ISSUE TITLE
Errors while parsing arguments

### ISSUE THREAD

**Issue by t0dd** [bevanhunt/meteor-leaflet#19]
Running meteor 1.0.5 - while attempting to install the plugin - $ meteor add beavanhunt:leaflet
received the following -

 => Errors while parsing arguments:           
                                              
While adding package beavanhunt:leaflet:
error: no such package

**Comment by bevanhunt** [comment]
Sorry for the delay - the new version of this package [0.3.13](https://github.com/bevanhunt/meteor-leaflet/releases/tag/0.3.13) should fix this problem. Thanks for the bug report.

**Comment by bevanhunt** [comment]
It is bevanhunt:leaflet not beavanhunt:leaflet - cheers
I made put the package into an organization so one doesn't have to use my name - but there is no firm date for that yet.

**Comment by bevanhunt** [comment]
https://github.com/bevanhunt/meteor-leaflet/commit/2a9cdacaaaa89f4967207bd715b2ec91b87519bc - I didn't realize the typo was in the readme - my bad - it is now fixed - cheers!

**Comment by t0dd** [comment]
Thanks!
