### ISSUE TITLE
add support for dynamic marker popups

### ISSUE THREAD

**Issue by bevanhunt** [bevanhunt/meteor-leaflet#24]
The most user requested feature https://github.com/bevanhunt/meteor-leaflet/issues/1 - it is about time it was built-in to this library.

**Comment by FickleLife** [comment]
+1 !

**Comment by bevanhunt** [comment]
Also create a branch in the demo app for this feature and link to it in the readme.

**Comment by bevanhunt** [comment]
Documented how to in the readme - a wrapper would only wrap one function - Blaze.renderWithData something that the app authors need to understand. Will write a demo app.
