### ISSUE TITLE
Limit collection to items show on the map

### ISSUE THREAD

**Issue by kaypro4** [bevanhunt/meteor-leaflet#28]
Hello, I'm loving using this package for my app but running into a challenge with limiting the collection based on what's displayed on the map.  Essentially I would like to pan/zoom around the map and have the collection items listed along side the map limited to just the markers that are displayed on the map.

Can anyone help out with how I would do this conceptually?

Thanks

**Comment by kaypro4** [comment]
Alright, this may be getting me close:

map.on('moveend', function() { 
	     console.log(map.getBounds());
});

Now I just need to figure out how to filter the collection based on these bounds.  Please let me know if anyone has ideas on how to do that the right way.  Thanks.

**Comment by bevanhunt** [comment]
@kaypro4 http://joshowens.me/using-mongodb-geospatial-index-with-meteor-js/

**Comment by bevanhunt** [comment]
@kaypro4 as I haven't heard back from you and this is not an issue with library I am closing the issue - cheers.

**Comment by bevanhunt** [comment]
@kaypro4 thanks for the feedback and I am glad you are liking the library - I have created a feature investigation ticket for the next release - https://github.com/bevanhunt/meteor-leaflet/issues/29
