### ISSUE TITLE
add leaflet animate marker support

### ISSUE THREAD

**Issue by bevanhunt** [bevanhunt/meteor-leaflet#30]
The ability to animate markers enables a whole new set of applications that can be built. This combines well with Meteor's real-time collections. This is the link ot the library https://github.com/openplans/leaflet.animatedmarker

**Comment by bevanhunt** [comment]
This should be its own package.

**Comment by mikeatlas** [comment]
agreed, keep the plugins for leaflet separate from your repo. too much to maintain otherwise.
