### ISSUE TITLE
create static mode

### ISSUE THREAD

**Issue by bevanhunt** [bevanhunt/meteor-leaflet#31]
Integrate this library https://atmospherejs.com/meteorhacks/inject-initial

Idea from https://github.com/waeltken/leaflet-prefer-canvas/

cc @waelken

**Comment by bevanhunt** [comment]
CANVAS	Boolean	depends	True if Canvas is used for vector rendering (Android 2). You can also force this by setting global variable L_PREFER_CANVAS to true before the Leaflet include on your page — sometimes it can increase performance dramatically when rendering thousands of circle markers, but currently suffers from a bug that causes removing such layers to be extremely slow.

http://leafletjs.com/reference.html

Should include functionality in Meteor Leaflet and it make it optional.

**Comment by bevanhunt** [comment]
Should be used for optimal static rendering. This is a requirement of https://github.com/bevanhunt/meteor-leaflet/issues/39

**Comment by bevanhunt** [comment]
See if this is still needed after 1.0 release.

**Comment by bevanhunt** [comment]
This should be put into a Leaflet MarkerCluster package.

**Comment by mikeatlas** [comment]
Leaflet 1.0 makes preferCanvas a map startup option instead of a global pre-set variable.
