### ISSUE TITLE
Integrate Leaflet Search

### ISSUE THREAD

**Issue by bevanhunt** [bevanhunt/meteor-leaflet#36]
https://github.com/stefanocudini/leaflet-search

https://www.npmjs.com/package/leaflet-search

I use this in all my map apps.

**Comment by bevanhunt** [comment]
Should be its own package.

**Comment by mikeatlas** [comment]
agreed, keep the plugins for leaflet separate from your repo. too much to maintain otherwise.

**Comment by stefanocudini** [comment]
@bevanhunt  you can use this pkg:
https://atmospherejs.com/stefcud/leaflet-search

I'll maintain it for ever

FYI @mikeatlas

**Comment by bevanhunt** [comment]
@stefanocudini thanks for updating your leaflet search package. I would like to keep it separate. Because your awesome leaflet and meteor skills I added you as a contributor to both this library and the demo repo as well. Cheers and welcome to the team :smile:

**Comment by stefanocudini** [comment]
Yes I agree, now you can use leaflet-search like dependency package inside your app
