### ISSUE TITLE
upgrade leaflet to 1.0.0-beta1

### ISSUE THREAD

**Issue by bevanhunt** [bevanhunt/meteor-leaflet#40]
Huge performance improvements - contains breaking changes - so should up this package to 1.0.0 - must test locally with all other included libraries.

**Comment by bevanhunt** [comment]
waiting until Leaflet MerkerCluster supports new Leaflet version - https://github.com/Leaflet/Leaflet.markercluster/issues/528

**Comment by bevanhunt** [comment]
Open WIP PR https://github.com/bevanhunt/meteor-leaflet/pull/41

**Comment by derwaldgeist** [comment]
I just ran into an issue with the leaflet-image plugin, which is not compatible with 1.0.0-beta2. It would be great to have branch of this package including the officially supported and documented Leaflet version (0.7).

**Comment by bevanhunt** [comment]
@derwaldgeist OK - I will create a new ticket.

**Comment by derwaldgeist** [comment]
Thanks!

**Comment by bevanhunt** [comment]
@derwaldgeist new version is published on Atmosphere.
