### ISSUE TITLE
error trim on pkg added

### ISSUE THREAD

**Issue by stefanocudini** [bevanhunt/meteor-leaflet#47]
after I'm added this pkg in place of old leaflet 0.7.3, show this error in console at startup:

**Uncaught TypeError: Cannot read property 'trim' of undefined**

**Comment by bevanhunt** [comment]
@stefanocudini I did a quick google search and it could be related to marker cluster. Marker cluster has not been updated to support leaflet 1.0.0-beta.1 so I had to remove it in my 1.0.0 release. If this isn't your issue - I haven't seen this error - so I will need a repo case in code - cheers.

**Comment by stefanocudini** [comment]
uohh tnk!  Yes I'm using  L.Markercluster!!

**Comment by bevanhunt** [comment]
Best to stick with 0.3.18 then - sorry about that.

**Comment by stefanocudini** [comment]
0.3.18 or 0.3.18??

**Comment by bevanhunt** [comment]
0.3.18 - is the only branch that has marker cluster and leaflet 0.7.3 - cheers.

**Comment by stefanocudini** [comment]
Sorry @bevanhunt I don't found 0.3.18 version of L.MarkerCluster:
https://github.com/Leaflet/Leaflet.markercluster/releases

**Comment by bevanhunt** [comment]
@stefanocudini this libraries 0.3.18 - https://github.com/bevanhunt/meteor-leaflet/releases/tag/0.3.18

**Comment by stefanocudini** [comment]
ok tnk @bevanhunt I'm using this version of pkg until the bug is not solved in markercluster, now it work
