### ISSUE TITLE
Cant Load the Map

### ISSUE THREAD

**Issue by Ethaan** [bevanhunt/meteor-leaflet#48]
Hi

This could be a noob question, but i just cant make my map appears.

it should be simply but it dont works.

here is the link to the repo.

https://github.com/Ethaan/mexico-tourism

and more further here is the .js file.

https://github.com/Ethaan/mexico-tourism/blob/master/packages/mt-landing-map/client/views/landing-map/landing-map.js

and the .html

https://github.com/Ethaan/mexico-tourism/blob/master/packages/mt-landing-map/client/views/landing-map/landing-map.html

If you have the time and clone this repo and run it, and then inspect the element you will see that the map is there loaded on the html, but it dosnt show up.

Bests

**Comment by Ethaan** [comment]
Seems like i was missing.

     L.tileLayer.provider('Thunderforest.Outdoors').addTo(map);

**Comment by bevanhunt** [comment]
@Ethaan thanks for letting me know - cheers!
