### ISSUE TITLE
latlng is undefined

### ISSUE THREAD

**Issue by iamlasse** [bevanhunt/meteor-leaflet#55]
Anyone run into this issue?

```
TypeError: latlng is undefined meteor.js:888:11
L.Projection.SphericalMercator.project@http://127.0.0.1:8000/packages/bevanhunt_leaflet.js?b696c1f6418c4dcd41cddbe44d079f0c00516fcf:1475:7
```

**Comment by noahfkennedy** [comment]
I'm also having trouble with this. I believe that it has something to do with an asynchronous data call; When grabbing latlng, the code continues running before the .latlng data has been brought up. I managed to make some partial fixes but to date I am still having trouble running a template event function.
