### ISSUE TITLE
erratic zooming behaviour

### ISSUE THREAD

**Issue by willemx** [bevanhunt/meteor-leaflet#61]
My app has some strange zooming behaviour: when zooming out, the drawn polygon moves south-east and returns to its correct postion when the zoom operation ends. When zooming in, the drawn polygon moves north-west and returns to its correct postion when the zoom operation ends.

this is my app:

    Template.map.rendered = function() {
      var map = L.map('map').setView([51.505, -0.09], 13);

      L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: "&copy; <a href='http://openstreetmap.org/copyright'>OpenStreetMap</a> contributors"
      }).addTo(map);

      var polygon = L.polygon([
        [51.509, -0.08],
        [51.503, -0.06],
        [51.51, -0.047]
      ]).addTo(map);
    };

If I replace your (V1.0.0 beta2) package bevanhunt:leaflet with fuatsengul:leaflet (V0.7.3) everything is ok again.
Probably nothing to do with your package, but I could not find this problem in the leaflet github issues.
Any suggestions?

**Comment by bevanhunt** [comment]
IMO - It only does this when the tileset hasn't fully loaded. This seems like a Lealfet 1.0.0-beta2 bug - I suggest filing it on the Leaflet repo. Thanks for the report!

**Comment by IvanSanchez** [comment]
Leaflet dev here.

Whether a tile layer has completely loaded or not does not have any effect on the positioning of SVG/Canvas vector layers. I can demonstrate here: http://playground-leaflet.rhcloud.com/bet/edit?html,output

Also, it is possible to have a map with no tiles, just vectors. It would be a good idea to try if the bug still reproduces without a tile layer.

@bevanhunt I'm afraid I must bounce this bug back to you :-/

**Comment by willemx** [comment]
I tried without adding a tile layer. The bug is still there...

**Comment by willemx** [comment]
Not sure if this info is of any value diagnosing the problem, but If I set { zoomAnimation: false } for the map, the erratic content movement is gone.
So, something todo with animations must have changed between leaflet V0.7 and V1B2 that a meteor app like mine does not agree with...
