### ISSUE TITLE
Unable to pan a leaflet map inside an ionic slide box

### ISSUE THREAD

**Issue by DimDrop** [bevanhunt/meteor-leaflet#63]
There is a leaflet map using div tag inside a slide within a slide box. The map shows up but will not allow any panning although zoom works. This looks like the swipe ability of the slide box is interfering with the swipe of the map. The swipe for the slide box has been disabled using the slide box delegate's enableSlide method. Remove slide box tags and the map can pan. This is within an angular-meteor app using ionic and bevanhunt:leaflet package. 

https://forum.ionicframework.com/t/unable-to-pan-a-leaflet-map-inside-an-ionic-slide-box/38280

**Comment by bevanhunt** [comment]
I am just wrapping the leaflet beta-2 library - a bug would only occur in the leaflet library (which I don't maintain) or in the interaction between Meteor and Leaflet (which I can't control). Sorry about that. Thanks for the report.
