### ISSUE TITLE
marker showing missing image icon

### ISSUE THREAD

**Issue by HeidiDurhuus** [bevanhunt/meteor-leaflet#66]
I don't know how to replicate the error, but one day the marker just shows a missing image icon.

Here is the code in the .js file:

  var maxZoom = 18;
  var latlng = null;
  var marker = null;

  L.Icon.Default.imagePath = 'packages/bevanhunt_leaflet/images';
  map = L.map('map', {    //map is a global variable
    center: [56.00, 10.00],
    zoom: 5
  });

  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
  attribution: 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
  maxZoom: 18
  }).addTo(map);

  //register eventlistener to map
  map.on('click', function(e) {

    latlng = e.latlng;
    var zoom = map.getZoom();

    //if zoom is equal or less than 18
    if(zoom < maxZoom){
      map.panTo(latlng);
      map.setZoom(map.getZoom()+2);
    }
    if(zoom == maxZoom){
      if(!marker){
        marker = L.marker(latlng).addTo(map);
      }else{
        map.removeLayer(marker);
        marker = L.marker(latlng).addTo(map);
      }
    }
  });

It seems like the path 'packages/bevanhunt_leaflet/images' stopped working, because when I moved the images to the projects public folder, the pointer showed up again.

**Comment by Smittey** [comment]
To add to this, I attempted to override it with the following url:
"https://npmcdn.com/leaflet@1.0.0-rc.3/dist/images/marker-icon.png" 

The image the map tried to render was the following:
https://npmcdn.com/leaflet@1.0.0-rc.3/dist/images/marker-icon.png/marker-icon.png


Nowhere in my code have I tried to append 'marker-icon.png' to the path.

**Comment by bevanhunt** [comment]
It was the packages/bevanhunt_leaflet/images - it needed to be packages/bevanhunt_leaflet/images/ - notice the trailing slash. I updated the documentation and demo app. Cheers.
