### ISSUE TITLE
Leaflet 1.0.0 - FlyTo method

### ISSUE THREAD

**Issue by krem06** [bevanhunt/meteor-leaflet#69]
Hi there,

I am currently using your package (thanks by the way !) and trying to add a nice fly effect when I change map position. On leaflet doc, I found the flyto method but it seems that it is only available from leaflet 1.0.0.

When I try to access it with your plugin I get 'Uncaught TypeError: map.flyTo is not a function'. I think it's because I am using leaflet 0.7.7...

In the doc you mention the 1.0.0-beta2 version of leaflet associated to your plugin version 1.3.1.

Should I downgrade to 1.3.2 to use flyTo ?
If not, what should I do to use the flyto method ?

Thank you

**Comment by bevanhunt** [comment]
I will be releasing a new version based on 1.0.0 - probably later today. I will update this ticket when I do to let you know - cheers.

**Comment by bevanhunt** [comment]
Pubilshed 3.0.1 - which includes Leaflet 1.0.0 - have fun! Cheers!

**Comment by krem06** [comment]
Awesome, I can fly now !!

Thanks
