### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by fillipefeitosa** [bevanhunt/meteor-leaflet#79]
Hey, thanks for sharing this package.

Are there plans to update to the last leaflet version?  Is this repository still being maintained?

**Comment by bevanhunt** [comment]
Yes - I was just waiting for somebody to point it out. I wasn't sure if anybody is still using it - as Meteor isn't very popular anymore. But since you asked I will update it - next week when I have some time. I will update this issue when that is complete. Thanks!

**Comment by fillipefeitosa** [comment]
Thanks for your time!

Is there anything I could do to help?

Meteor community are getting better and a lot of updates made people comeback to test it again.

**Comment by bevanhunt** [comment]
Sorry, I got really busy. I will accept a PR to update it. If time permits I will look at it next week. Thanks!

**Comment by fillipefeitosa** [comment]
Done a small update in the #80 PR. I tested it with Meteor 1.8.1

**Comment by truemagic-coder** [comment]
@fillipefeitosa thanks - updated the project and published!
